name: tfsec - Security Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
    tfsec-base:
        name: tfsec sarif report - BASE
        runs-on: ubuntu-latest

        steps:
            -   name: Clone repo
                uses: actions/checkout@main

            -   name: tfsec base
                uses: tfsec/tfsec-sarif-action@master
                with:
                    sarif_file: tfsec.sarif                  

            -   name: Upload base SARIF file
                uses: github/codeql-action/upload-sarif@v1
                with:
                    # Path to SARIF file relative to the root of the repository
                    sarif_file: tfsec.sarif

    tfsec-aws-backend:
        name: tfsec sarif report - AWS-BACKEND
        runs-on: ubuntu-latest

        steps:
            -   name: Clone repo
                uses: actions/checkout@main

            -   name: tfsec backend
                uses: tfsec/tfsec-sarif-action@master
                with:
                    working_directory: aws-backend
                    sarif_file: tfsec-aws-backend.sarif

            -   name: Upload base SARIF file
                uses: github/codeql-action/upload-sarif@v1
                with:
                    # Path to SARIF file relative to the root of the repository
                    sarif_file: tfsec-aws-backend.sarif

    tfsec-three-tier-app-with-vpc:
        name: tfsec sarif report - THREE TIER WEB APP WITH VPC
        runs-on: ubuntu-latest

        steps:
            -   name: Clone repo
                uses: actions/checkout@main

            -   name: tfsec backend
                uses: tfsec/tfsec-sarif-action@master
                with:
                    working_directory: three-tier-web-app-with-vpc
                    sarif_file: tfsec-three-tier-web-app-with-vpc.sarif

            -   name: Upload base SARIF file
                uses: github/codeql-action/upload-sarif@v1
                with:
                    # Path to SARIF file relative to the root of the repository
                    sarif_file: tfsec-three-tier-web-app-with-vpc.sarif